using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection.Emit;
using UnityEngine;
using UnityEngine.TerrainUtils;

namespace Dungeon.Generator {
    /// <summary>
    /// The dungeon
    /// </summary>
    public class Dungeon {
        // TODO: change this back to List, Dict is redundant
        internal Dictionary<Vector2Int, Room> rooms = new();

        // variables controlling the room's generation
        /// <summary>
        /// List of rooms the generator can choose from
        /// </summary>
        public (RoomType, Vector2Int[])[] Options { get; private set; }
        /// <summary>
        /// The length of the path from start room to end room
        /// </summary>
        public uint MainPathLength { get; private set; }
        /// <summary>
        /// <para>The minimum number of rooms for each roomtype.</para>
        /// If a roomtype is not hashed to anything, it is considered as unrestricted (i.e. no minimum).<br />
        /// If the dictionary is empty, it is considered as no minimum for all rooms
        /// </summary>
        public Dictionary<RoomType, uint> MinNumRooms { get; private set; }
        /// <summary>
        /// <para>The maximum number of rooms for each roomtype.</para>
        /// If a roomtype is not hashed to anything, it is considered as unlimited (i.e. no maximum).<br />
        /// If the dictionary is empty, it is considered as no minimum for all rooms
        /// </summary>
        public Dictionary<RoomType, uint> MaxNumRooms { get; private set; }
        /// <summary>
        /// The maximum number of rooms in the dungeon
        /// </summary>
        public uint MaxTotalRooms { get; private set; }

        Dictionary<RoomType, uint> numRooms = new();

        internal Dictionary<(Room, Room), Connection> Connections { get; private set; } = new();

        /// <summary>
        /// Generates the dungeon
        /// </summary>
        public Dungeon((RoomType, Vector2Int[])[] options, uint mainPathLength, Dictionary<RoomType, uint> minNumRooms, Dictionary<RoomType, uint> maxNumRooms, uint maxTotalRooms) {
            Options = options;
            MainPathLength = mainPathLength;
            MinNumRooms = minNumRooms;
            MaxNumRooms = maxNumRooms;
            MaxTotalRooms = maxTotalRooms;
            Generate();
        }

        /// <summary>
        /// All the rooms generated by the generator
        /// </summary>
        public IEnumerable<(RoomType, Vector2Int[])> GeneratedRooms => rooms.Select(r => (r.Value.Type, r.Value.Blocks.Select(b => b.coordinate).ToArray()));

        /// <summary>
        /// The smallest XY coordinates in the entire dungeon
        /// </summary>
        public Vector2Int MinCorner => new(rooms.Min(r => r.Value.MinCorner.x), rooms.Min(r => r.Value.MinCorner.y));
        /// <summary>
        /// The largest XY coordinates in the entire dungeon
        /// </summary>
        public Vector2Int MaxCorner => new(rooms.Max(r => r.Value.MaxCorner.x), rooms.Max(r => r.Value.MaxCorner.y));



        /// <summary>
        /// The big thing that generates the dungeon
        /// </summary>
        void Generate() {
            // the starting room
            rooms.Add(new(0, 0), new(0, 0, RoomType.Start, new Block(0, 0)));
            Room prev = rooms[new(0, 0)];
            int failCount = 0;
            // generate main path
            for (int i = 0; i < MainPathLength; i++) {
                bool createdRoom = false;
                // insert callback hell meme but for loop

                // loop through rom where rom = a potential room
                foreach ((RoomType, Vector2Int[]) rom in RoomSpawnList) {
                    Room toSpawn = (i == MainPathLength-1)? new(0, 0, RoomType.Final, new Block(0,0)): new(0, 0, rom.Item1, rom.Item2.Select(x=>new Block(x)).ToArray());

                    // loop through blk where blk = each block of the previous room
                    IEnumerable<Block> shuffledPrevBlocks = prev.Blocks.OrderBy(b => Random.value);
                    foreach (Block blk in shuffledPrevBlocks) {
                        // loop through edg where edg = all valid edges of blk
                        IEnumerable<Vector2Int> shuffledEdges = EdgeOf(blk).OrderBy(x => Random.value);
                        foreach (Vector2Int edg in shuffledEdges) {

                            Vector2Int dist = edg - blk.coordinate;

                            // loop through rot where rot = all rotations for the room
                            IEnumerable<uint> rotations = new uint[] { 0, 1, 2, 3 }.OrderBy(x => Random.value);
                            foreach (uint rot in rotations) {
                                // blocks that can join the chosen block from prev
                                toSpawn.NormalizedRotation = rot;

                                // loop through com where com = all block coordinates of the rotated chosen room that can be connected to blk
                                IEnumerable<Vector2Int> compatibleBlockCoords = toSpawn.Blocks.Select(b => b.coordinate).Where(c => !toSpawn.Contains(c - dist)).OrderBy(c => Random.value);
                                foreach (Vector2Int com in compatibleBlockCoords) {
                                    // set the room's center s.t. com == edg
                                    // center + com = edg
                                    // => center = edg - com
                                    toSpawn.Center = edg - com;

                                    if (!rooms.Any(r => r.Value.Collides(toSpawn))) {
                                        // finally, spawn the room
                                        rooms.Add(toSpawn.Center, toSpawn);
                                        Connections.Add((prev, toSpawn), new(prev, toSpawn, blk.coordinate, edg)); // since edg will be where toSpawn's connector is at
                                        createdRoom = true;
                                        prev = toSpawn;
                                        break;
                                    }
                                }
                                if (createdRoom) break;
                                toSpawn.Center = Vector2Int.zero;
                            }
                            if (createdRoom) break;
                            toSpawn.NormalizedRotation = 0;
                        }
                        if (createdRoom) break;
                    }
                }

                if (!createdRoom) {
                    i--;
                    failCount++;
                    if (failCount >= 1000) {
                        Debug.Log("Too many failures, aborting...");
                        return;
                    }
                }
            }
        }


        IEnumerable<(RoomType, Vector2Int[])> RoomSpawnList => Options.Where(x => MaxNumRooms is null || !MaxNumRooms.ContainsKey(x.Item1) || !numRooms.ContainsKey(x.Item1) || numRooms[x.Item1] <= MaxNumRooms[x.Item1])
            .OrderBy(x=>Random.value);

        IEnumerable<Vector2Int> EdgeOf(in Block b) => b.Edges.Where(e => !rooms.Any(r => r.Value.Contains(e)));


        IEnumerable<Vector2Int> Edges => rooms.Select(r => r.Value.UnfilteredEdges)
                                            .SelectMany(list => list)
                                            .Distinct()
                                            .Where(c => !rooms.Any(r => r.Value.Contains(c)));
        IEnumerable<Vector2Int> RandomizedEdges => Edges.OrderBy(_ => Random.value);




        public void Print() {
            char[] roomTypeIndicators = new char[] {'s', 'm', 'f'};
            Vector2Int min = MinCorner, max = MaxCorner;
            Dictionary<Vector2Int, string> indicator = new Dictionary<Vector2Int, string>();
            string toPrint = "";
            for (int y = max.y; y >= min.y; y--) {
                for (int x = min.x; x <= max.x; x++) {
                    IEnumerable<Room> targetRoom = rooms.Where(r => r.Value.Contains(new Vector2Int(x, y))).Select(r=>r.Value);
                    if (targetRoom.Count() != 0) {
                        Room target = targetRoom.FirstOrDefault();
                        if (!indicator.ContainsKey(target.Center)) {
                            string toAdd = "";
                            int num = indicator.Count();
                            // translate indicator.count to aaa, aab, ...
                            for (int i = 0; i < Mathf.Ceil(Mathf.Log(rooms.Count(), 26)); i++) {
                                toAdd = (char)('a' + num % 26) + toAdd;
                                num /= 26;
                            }
                            indicator.Add(target.Center, toAdd);
                        }

                        toPrint += roomTypeIndicators[(int)target.Type] + indicator[target.Center];

                    }
                    else {
                        // print spaces to cover room type indicator + characters representing a dungeon room
                        for (int i = 0; i < 1+Mathf.Ceil(Mathf.Log(rooms.Count, 26)); i++) {
                            toPrint += " ";
                        }
                    }

                    toPrint += "\t";
                }
                toPrint += "\n";
            }
            Debug.Log(toPrint);
        }
    }

    public static class Driver {
        public static void Main() {
            (RoomType, Vector2Int[])[] options = {
                (RoomType.Mob, new Vector2Int[]{Vector2Int.zero}), // 1x1
                (RoomType.Mob, new Vector2Int[]{Vector2Int.zero, Vector2Int.right}), // 1x2
                (RoomType.Mob, new Vector2Int[]{Vector2Int.zero, Vector2Int.up, Vector2Int.right}), // L
                (RoomType.Mob, new Vector2Int[]{Vector2Int.zero, Vector2Int.right, Vector2Int.right+Vector2Int.right}) // 1x3
            };
            Dungeon d = new Dungeon(options, 5, null, null, 10000);
            d.Print();
        }
    }
}