using JetBrains.Annotations;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection.Emit;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;
using UnityEngine.TerrainUtils;

namespace Dungeon.Generator {
    /// <summary>
    /// The dungeon
    /// </summary>
    public class Dungeon {
        internal List<Room> rooms = new();
        /// <summary>
        /// jagged list of rooms grouped by abs layer (|y| - y = -1 => abs layer = |-1| = 1)
        /// </summary>
        internal List<List<Room>> layeredRooms = new();

        // variables controlling the room's generation
        /// <summary>
        /// List of rooms the generator can choose from
        /// </summary>
        public (string, RoomType, Vector2Int[])[] Options { get; private set; }
        /// <summary>
        /// The length of the path from start room to final room, including the start and final room
        /// </summary>
        public uint MainPathLength { get; private set; }
        /// <summary>
        /// Number of rooms to include for each room type, do not include start and final room
        /// </summary>
        public Dictionary<RoomType, uint> NumRooms = new();
        /// <summary>
        /// number of rooms left to spawn for each room type
        /// </summary>
        Dictionary<RoomType, uint> spawnRequirement;
        /// <summary>
        /// The expected length of a side path *when it is generated* (i.e. if another side path links from a side path, the original one's length is expected to be doubled)
        /// </summary>
        public uint ExpectedSidePathLength { get; private set; }
        /// <summary>
        /// Generation: given a side room is generated. It has a probability p of being extended, and so is its extension. <br />
        /// Given we want to generate s side paths on average, find p in terms of s.<br />
        /// E(X) + 1 = s
        /// 1/(1-p) - 1 + 1 = s
        /// => 1-p = 1/s
        /// => p = 1-1/s
        /// </summary>
        float SideRoomChainProbability => 1 - 1f / ExpectedSidePathLength;


        internal List<Connection> Connections { get; private set; } = new();

        /// <summary>
        /// Generates the dungeon
        /// </summary>
        public Dungeon((string, RoomType, Vector2Int[])[] options, uint mainPathLength, Dictionary<RoomType, uint> numRooms, bool isLayered = true, uint expectedSidePathLength = 2) {
            if (!options.All(x =>numRooms.ContainsKey(x.Item2)))
                throw new System.Exception("All roomtypes in options must appear in numRooms once");
            if (mainPathLength > numRooms.Sum(x=>x.Value))
                throw new System.Exception("The main path's length cannot be larger than the number of rooms");
            if (mainPathLength != numRooms.Sum(x=>x.Value) && expectedSidePathLength == 0)
                throw new System.Exception("If the main paths's length is smaller than the number of rooms, expectedSidePathLength must be non-zero");
            Options = options;
            MainPathLength = mainPathLength;
            NumRooms = numRooms;
            spawnRequirement = numRooms.ToDictionary(x=>x.Key, x=>x.Value);
            ExpectedSidePathLength = expectedSidePathLength;
            Generate(isLayered);
        }

        /// <summary>
        /// All the rooms generated by the generator
        /// </summary>
        public IEnumerable<(RoomType, Vector3Int[])> GeneratedRooms => rooms.Select(r => (r.Type, r.Blocks.Select(b => b.coordinate).ToArray()));

        /// <summary>
        /// The smallest XYZ coordinates respectively in the entire dungeon
        /// </summary>
        public Vector3Int MinCorner => new(rooms.Min(r => r.MinCorner.x), rooms.Min(r => r.MinCorner.y), rooms.Min(r => r.MinCorner.z));
        /// <summary>
        /// The largest XYZ coordinates respectively in the entire dungeon
        /// </summary>
        public Vector3Int MaxCorner => new(rooms.Max(r => r.MaxCorner.x), rooms.Max(r => r.MinCorner.y), rooms.Max(r => r.MaxCorner.z));



        /// <summary>
        /// The big thing that generates the dungeon
        /// </summary>
        /// <param name="isLayered">Whether the dungeon should expand vertically (y)</param>
        void Generate(in bool isLayered) {
            GenerateMainPath(in isLayered);
            GenerateSidePath();
        }

        /// <summary>
        /// Main path generator
        /// </summary>
        /// <param name="isLayered">whether</param>
        void GenerateMainPath(in bool isLayered) {
        Redo:
            // the starting room
            rooms.Add(new(0, 0, "start", RoomType.Start, new Block(0, 0)));
            layeredRooms.Add(new());
            layeredRooms[0].Add(rooms[0]);
            Room prev = rooms[0];
            int consecutiveFailCount = 0;
            // generate main path
            for (int i = 0; i < MainPathLength-1; i++) { // -1 as startRoom counts as a room
                bool createdRoom = false;
                // insert callback hell meme but for loop

                // loop through rom where rom = a potential room
                foreach ((string, RoomType, Vector2Int[]) rom in RoomSpawnList) {
                    Room toSpawn = (i == MainPathLength-2)? new(0, 0, "final", RoomType.Final, new Block(0, 0)): new(0, 0, rom.Item1, rom.Item2,
                        rom.Item3.Select(x=>new Block(x.x, x.y)).ToArray());

                    // loop through blk where blk = each block of the previous room
                    IEnumerable<Block> shuffledPrevBlocks = prev.Blocks.OrderBy(b => Random.value);
                    if (prev.Type == RoomType.Ladder) shuffledPrevBlocks = shuffledPrevBlocks.Where(b => b.coordinate != prev.Center); // skip the upper block if ladder
                    foreach (Block blk in shuffledPrevBlocks) {
                        // loop through edg where edg = all valid edges of blk
                        IEnumerable<Vector3Int> shuffledEdges = EdgeOf(blk, layeredRooms.Count-1).OrderBy(x => Random.value);
                        foreach (Vector3Int edg in shuffledEdges) {
                            createdRoom = TrySpawnRoom(toSpawn, prev, blk, edg);
                            if (createdRoom) {
                                prev = rooms[^1];
                                break;
                            }
                        }
                        if (createdRoom) break;
                    }
                    if (createdRoom) break;
                }

                if (!createdRoom) {
                    i--;
                    consecutiveFailCount++;
                    if (consecutiveFailCount >= 10) {

                        if (isLayered)
                        {

                            if (spawnRequirement.ContainsKey(prev.Type)) spawnRequirement[prev.Type]++;

                            layeredRooms.Add(new());
                            int index = Connections.Count - 1;
                            Room r = new(Connections[index].posB, "ladder", RoomType.Ladder, new Block(new Vector3Int(0, -1, 0)));
                            Connections[index] = new Connection(Connections[index].a, r, Connections[index].posA, Connections[index].posB);
                            rooms.Remove(prev);
                            rooms.Add(r);
                            // a ladder room will appear in both both y = -i-1 and y = -i
                            layeredRooms[^1].Add(r);
                            layeredRooms[^2].Add(r);
                            prev = r;
                            i--; // this room should not be counted towards no. of rooms
                        }

                        else {
                            spawnRequirement = NumRooms.ToDictionary(x => x.Key, x => x.Value);
                            rooms.Clear();
                            Connections.Clear();
                            goto Redo;
                        }
                    }
                } else consecutiveFailCount = 0;
            }
        }

        void GenerateSidePath() {
            // for each iteration, always try to extend the first element of it if it is not empty
            Room extendCandidate = null;
            while (spawnRequirement.Sum(x => x.Value) > 0) {

                // choose an edge
                Vector3Int chosenEdge = extendCandidate is not null ?
                    EdgeOf(extendCandidate).OrderBy(_ => Random.value).FirstOrDefault() :
                    Edges.OrderBy(_ => Random.value).FirstOrDefault();
                // associate the edge with the correct random block
                Room associatedRoom = extendCandidate is not null?
                    extendCandidate:
                    layeredRooms[-chosenEdge.y]
                        .Where(r=>r.Type != RoomType.Final && r.Type != RoomType.Start && r.Blocks.Any(b=>b.HammingDistance(chosenEdge) == 1))
                        .OrderBy(_ => Random.value)
                        .FirstOrDefault();
                Block associatedBlock = associatedRoom.Blocks
                    .Where(b => b.HammingDistance(chosenEdge) == 1)
                    .OrderBy(_ => Random.value)
                    .FirstOrDefault();
                // try to spawn a room
                bool spawnedRoom = false;

                foreach (Room toSpawn in RoomCandidates) {
                    spawnedRoom = TrySpawnRoom(toSpawn, associatedRoom, associatedBlock, chosenEdge);
                    if (spawnedRoom) {
                        extendCandidate = Random.value < SideRoomChainProbability? toSpawn: null;
                        break;
                    }
                }
                if (!spawnedRoom) {
                    extendCandidate = null;
                }
            }
        }


        /// <summary>
        /// <para>Tries to spawn a room given a predetermined edge and block to spawn it at.</para>
        /// The algorithm will try to fit the room into the dungeon by trying: <br />
        /// -all rotation <br />
        /// -all positions of each rotation such that a block of the room is both in <c>e</c> and is next to <c>b</c>
        /// </summary>
        /// <param name="r">The candidate room</param>
        /// <param name="connector">The room that should be connected to the new room</param>
        /// <param name="b">Block the new room should be next to</param>
        /// <param name="e"></param>
        /// <returns>Whether the room is successfully spawned</returns>
        bool TrySpawnRoom(Room r, in Room connector, in Block b, in Vector3Int e) {
            r.NormalizedRotation = 0;
            foreach (uint rotation in new uint[]{ 0, 1, 2, 3}.OrderBy(x=>Random.value)) {
                r.Center = Vector3Int.zero;
                r.NormalizedRotation = rotation;
                Vector3Int dist = b.coordinate-e;
                // for some reason, this thing returned an enumerable of references to coordinates of r's blocks wtf
                IEnumerable<Vector3Int> compatibleBlockPositions = r.Blocks.Select(b => b.coordinate).Where(c => !r.Contains(c + dist)).ToList();
                foreach(Vector3Int pos in compatibleBlockPositions) {
                    // center + pos = edge => 
                    r.Center = e - pos;
                    if (layeredRooms[-e.y].All(r2=>!r2.Collides(r))) {
                        rooms.Add(r);
                        layeredRooms[-e.y].Add(r);
                        Connections.Add(new(connector, r, b.coordinate, e));
                        if (spawnRequirement.ContainsKey(r.Type)) spawnRequirement[r.Type]--;
                        return true;
                    }
                }
                
            }

            return false;
        }

        IEnumerable<(string, RoomType, Vector2Int[])> RoomSpawnList => Options.Where(x => spawnRequirement[x.Item2] > 0)
            .OrderBy(x=>Random.value);

        Room[] RoomCandidates => RoomSpawnList.Select(x => new Room(x)).ToArray();

        IEnumerable<Vector3Int> EdgeOf(in Block b) => b.Edges.Where(e => !rooms.Any(r => r.Contains(e)));
        IEnumerable<Vector3Int> EdgeOf(in Block b, int absLayer) => b.Edges.Where(e => !layeredRooms[absLayer].Any(r => r.Contains(e)));

        IEnumerable<Vector3Int> EdgeOf(in Room r) => r.UnfilteredEdges
            .Distinct()
            .Where(e => layeredRooms[-e.y].All(r2=>!r2.Contains(e)));

        IEnumerable<Vector3Int> Edges => rooms
                                        .Where(r=>r.Type != RoomType.Start && r.Type != RoomType.Final)
                                        .Select(r => r.UnfilteredEdges)
                                        .SelectMany(list => list)
                                        .Distinct()
                                        .Where(c => !rooms.Any(r => r.Contains(c)));




        public void Print() {
            string toPrint = "";
            Debug.Log(toPrint);
            toPrint = "";
            foreach (Room r in rooms) {
                toPrint += $"{r.Name}: {r.Center}, {r.NormalizedRotation*90}\n";
            }
            Debug.Log(toPrint);
        }

        public List<GameObject> Visualize() {
            List<GameObject> objects = new();
            int minY = MinCorner.y;
            foreach (Room r in rooms) {
                GameObject go = MonoBehaviour.Instantiate(Resources.Load<GameObject>($"RoomVisualizer/{r.Name}"));
                go.transform.position = r.Center - new Vector3(0, minY, 0);
                go.transform.localEulerAngles = new(0, r.RotationInGame,0);
                objects.Add(go);
            }
            string connSource = "connection_main";
            foreach (Connection c in Connections) {
                GameObject go = MonoBehaviour.Instantiate(Resources.Load<GameObject>($"RoomVisualizer/{connSource}"));
                go.transform.position = new((c.posA.x+c.posB.x)/2f,0.1f + System.Math.Min(c.posA.y, c.posB.y) - minY,(c.posA.z+c.posB.z)/2f);
                objects.Add(go);
                if (c.b.Type == RoomType.Final) connSource = "connection_side";
            }
            return objects;
        }
    }

    public static class Driver {

        static List<GameObject> SpawnedObjects;
        public static void Main() {
            if (SpawnedObjects != null) {
                foreach (GameObject obj in SpawnedObjects) { MonoBehaviour.Destroy(obj);}
            }


            (string, RoomType, Vector2Int[])[] options = {
                ("1x1mob", RoomType.Mob, new Vector2Int[]{}), // 1x1
                ("1x2mob", RoomType.Mob, new Vector2Int[]{Vector2Int.right}), // 1x2
                ("Lmob", RoomType.Mob, new Vector2Int[]{Vector2Int.up, Vector2Int.right}), // L
                ("1x3mob", RoomType.Mob, new Vector2Int[]{Vector2Int.left, Vector2Int.right}), // 1x3
                ("2x2mob", RoomType.Mob, new Vector2Int[]{Vector2Int.right, Vector2Int.up, Vector2Int.one}), // 2x2
                ("+mob", RoomType.Mob, new Vector2Int[] { Vector2Int.left, Vector2Int.right, Vector2Int.up, Vector2Int.down }) // +
            };
            Dungeon d = new Dungeon(options, 25, new(){ { RoomType.Mob, 40 }}, isLayered: true);
            d.Print();
            SpawnedObjects = d.Visualize();
        }
    }
}